id = "dark-2026-theme"
name = "Dark 2026"
version = "0.2.0"
schema_version = 1
authors = ["Copernicium282"]
description = "A custom Zed theme derived from VS Code's Dark 2026"
repository = "https://github.com/Copernicium282/zed-dark-2026"

themes = ["themes/dark-2026.json"]
